MyWorkManager/Models/Cover.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MyWorkManager.Models
{
    
    public class Cover
    {
        public int Id { get; set; }
        public  DateTime creatTime { get; set; }

        /// <summary>
        /// 衣领颜色
        /// </summary>
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "衣领颜色")]
        public CoverColour Colour { get; set; }
        /// <summary>
        /// 款式
        /// </summary>
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "款式")]
        public CoverSleeve Sleeve { get; set; }
        /// <summary>
        /// 大小
        /// </summary>

        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "大小")]
        public CoverSize Size { get; set; }
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "领用人")]
        public  string  workerName { get; set; }

        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "部门")]
        public string departmentName { get; set; }
        public  string Type { get; set; }
        
        [Required]
        [Range(1,2,ErrorMessage =("每人每次最多领取{1}件"))]
        [Display(Name = "领用数量")]
        
        public int Number { get; set; }
        




    }
}

MyWorkManager/Controllers/CoverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWorkManager.Dto;
using MyWorkManager.Models;
using MyWorkManager.QueryParameters;
using MyWorkManager.Servers;
using MyWorkManager.viewModels;

namespace MyWorkManager.Controllers
{
    [Authorize]
    public class CoverController : Controller
    {
        private readonly ICoverRepository _coverRepository;
        private readonly IMapper _mapper;
        
        public CoverController(ICoverRepository coverRepository,IMapper mapper)
        {
            _coverRepository = coverRepository;
            this._mapper = mapper;
        }
        [HttpGet]
        public async Task< IActionResult> Index()
        {
            var coverParameter = new CoverParameter() { PageNumber = 1,PageSize=10 ,StartTime=Convert.ToDateTime("1000-01-01"),EndTime=DateTime.UtcNow };
          var covers= await  _coverRepository.GetCoversAsync(coverParameter);//查询所有明细
            DateTime time = covers[0].creatTime;
            bool bo = time < DateTime.UtcNow;

            var groupcovers = covers.GroupBy(c => new { c.Colour, c.Sleeve, c.Size, c.Type }).Select(g => new { Colour = g.Key.Colour, Sleeve = g.Key.Sleeve, Size = g.Key.Size, Type = g.Key.Type, Number = g.Sum(testc => testc.Number) });//根据条件分组明细
            
            List<Cover> Coversgroup = new List<Cover>();
            foreach (var item in groupcovers)
            {
                if (item.Type == "入库")
                {
                    Cover cover = new Cover();
                    cover.Colour = item.Colour;
                    cover.Sleeve = item.Sleeve;
                    cover.Size = item.Size;
                    cover.Number = item.Number;
                    Coversgroup.Add(cover);
                }

            }
            foreach (var item in groupcovers)
            {
                foreach (var i in Coversgroup)
                {
                    if (item.Type == "出库" && i.Colour == item.Colour)
                    {
                        i.Number -= item.Number;

                    }
                }

            } //计算库存
            var coverstockparameter = new CoverStockParameterViewModel()
            {
                coverParameter = new CoverParameter() { /*PageNumber = covers.CurrentPage, PageSize = covers.PageSize */},
                covers = Coversgroup
            };//创建显示对象 包含查询参数 和明细


            return View(coverstockparameter);
        }
        [HttpPost]
        public async Task<IActionResult> Index(CoverParameter coverParameter)
        {
            coverParameter.StartTime = Convert.ToDateTime("1999-01-01");
            coverParameter.EndTime = DateTime.UtcNow;
           var covers = await _coverRepository.GetCoversAsync(coverParameter);//根据参数查询明细
            var groupcovers = covers.GroupBy(c => new { c.Colour, c.Sleeve, c.Size, c.Type }).Select(g => new { Colour = g.Key.Colour, Sleeve = g.Key.Sleeve, Size = g.Key.Size, Type = g.Key.Type, Number = g.Sum(testc => testc.Number) });//分组明细
            List<Cover> Coversgroup = new List<Cover>();
            foreach (var item in groupcovers)
            {
                if (item.Type == "入库")
                {
                    Cover cover = new Cover();
                    cover.Colour = item.Colour;
                    cover.Sleeve = item.Sleeve;
                    cover.Size = item.Size;
                    cover.Number = item.Number;
                    Coversgroup.Add(cover);
                }

            }
            foreach (var item in groupcovers)
            {
                foreach (var i in Coversgroup)
                {
                    if (item.Type == "出库" && i.Colour == item.Colour)
                    {
                        i.Number -= item.Number;

                    }
                }

            }//计算库存
            var coverstockparameter = new CoverStockParameterViewModel()
            {
                coverParameter = coverParameter,
                covers = Coversgroup
            };//创建显示对象包含参数和明细


            return View(coverstockparameter);
        }
        [Authorize(Roles =("Admin"))]
        [HttpGet]
        public async Task<IActionResult> AddCover(string covertype)
        {
            string[] cover = covertype.Split(',');
            
            CoverworkerDepartmentViewModel coverworkerDepartmentViewModel = new CoverworkerDepartmentViewModel() { 
                coverDto = new CoverDto() {creatTime=DateTime.UtcNow, Colour=(CoverColour) Enum.Parse(typeof(CoverColour), cover[0]), Sleeve= (CoverSleeve)Enum.Parse(typeof(CoverSleeve), cover[1]), Size= (CoverSize)Enum.Parse(typeof(CoverSize), cover[2]), Type= cover[3] },
                departments= (await _coverRepository.GetDepartmentsAsync()).Select(testc=>testc.Name).ToList(),
                workerSizes=(await _coverRepository.GetWorkerSizesAsync()).Select(w=>w.Name).ToList(),

        };
            

            return View(coverworkerDepartmentViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> AddCover(CoverDto   coverdto)
        {
            if (!ModelState.IsValid)
            {
                CoverworkerDepartmentViewModel coverworkerDepartmentViewModel = new CoverworkerDepartmentViewModel()
                {
                    coverDto = coverdto,
                    departments = (await _coverRepository.GetDepartmentsAsync()).Select(testc => testc.Name).ToList(),
                    workerSizes = (await _coverRepository.GetWorkerSizesAsync()).Select(w => w.Name).ToList(),

                };
                ModelState.AddModelError(string.Empty, "添加失败");
                return View(coverworkerDepartmentViewModel);
            }
            if (coverdto.Type.Contains("入库"))
            {
                coverdto.workerName = null;
                coverdto.departmentName = null;
            }
            _coverRepository.AddCoverAsync(_mapper.Map<CoverDto, Cover>(coverdto));
            if (coverdto.Type.Contains("出库"))
            {
                var workersize = _mapper.Map<CoverDto, WorkerSize>(coverdto);
                if (!_coverRepository.ExistWorker(coverdto.workerName))
                {

                    _coverRepository.AddWorkerSize(workersize);
                }
                var workersizeupdate = await _coverRepository.GetWorkerSizeByNameAsync(coverdto.workerName);
                workersizeupdate.Size = coverdto.Size;
                
            }
            await _coverRepository.SaveAsync();
            return RedirectToAction("Index");

        }

        [HttpGet]
      public IActionResult CoverDetail()
        {
            var coveredaitlparameter = new CoverDedailParameterViewModel()
            {
               coverParameter=new CoverParameter() { StartTime=DateTime.UtcNow,EndTime=DateTime.UtcNow, PageNumber = 1, PageSize =10 }
               
            };

            return View(coveredaitlparameter);
        }
        public async Task<IActionResult> CoverDetail(CoverParameter coverParameter)
        {
            var covers =await _coverRepository.GetCoversAsync(coverParameter);
            coverParameter.PageNumber = covers.CurrentPage;
            coverParameter.PageSize = covers.PageSize;
            coverParameter.totalPage = covers.TotalPage;
            var coveredaitlparameter = new CoverDedailParameterViewModel()
            {
                coverParameter = coverParameter,
                covers = covers
            };

            return View(coveredaitlparameter);

        }
    }
}

MyWorkManager/Views/Cover/AddCover.cshtml
@using MyWorkManager.viewModels;
@model CoverworkerDepartmentViewModel;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" />
    <title>工作服出入库</title>
    <!-- Bootstrap core CSS -->
    <link href="../bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <script src="~/bootstrap/dist/js/jquery-3.5.1.min.js"></script>
    <script src="~/bootstrap/dist/js/bootstrap.min.js"></script>
     <script type="text/javascript">
         $(document).ready(function () {
             var type = $("#Type").val
             if (type == "入库") {
                 $("#workerName").hide();
                 $("#departmentName").hide();
             };
         });
     </script>
</head>
<body>
    <div class="container">

        <div>
            <div class="page-header">
                <h1> <small></small></h1>
            </div>
        </div>
        <div class="container">


            <form class="form-horizontal" asp-controller="Cover" asp-action="AddCover" method="post">

                <div class="form-group">
                    <label asp-for="coverDto.creatTime" class="col-sm-2 control-label">日期</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control backcolour " id="creatTime"  asp-for="@Model.coverDto.creatTime" value=@Model.coverDto.creatTime.ToString("yyyy-MM-dd")>
                        <span asp-validation-for="@Model.coverDto.creatTime" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">颜色</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Colour" readonly asp-for="@Model.coverDto.Colour" value=@Model.coverDto.Colour>
                        <span asp-validation-for="@Model.coverDto.Colour" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">尺寸</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" readonly id="Sleeve" asp-for="@Model.coverDto.Sleeve">
                        <span asp-validation-for="@Model.coverDto.Sleeve" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">大小</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" readonly id="Size" asp-for="@Model.coverDto.Size">
                        <span asp-validation-for="@Model.coverDto.Size" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">数量</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="SumMoneny" asp-for="@Model.coverDto.Number">
                        <span asp-validation-for="@Model.coverDto.Number" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">类型</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="coverType" asp-for="@Model.coverDto.Type" value=@Model.coverDto.Type readonly>
                        <span asp-validation-for="@Model.coverDto.Type" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group" id="workerName">
                    <label asp-for="coverDto.workerName" class="col-sm-2 control-label">领用人</label>
                    <div class="col-sm-10">
                        <select class="form-control"  asp-for="@Model.coverDto.workerName" asp-items="@new SelectList(Model.workerSizes)"></select>
                        <span asp-validation-for="@Model.coverDto.workerName" style="color:red"></span>
                    </div>
                </div>

                <div class="form-group"  id="departmentName">
                    <label for="inputPassword3" class="col-sm-2 control-label">部门</label>
                    <div class="col-sm-10">
                        <select class="form-control"  asp-for="@Model.coverDto.departmentName" asp-items="@new SelectList(Model.departments)"></select>
                        @*<input type="text" class="form-control" id="Paypath" asp-for="Paypath">*@
                        <span asp-validation-for="@Model.coverDto.departmentName" style="color: red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">确认</button>
                        <a asp-controller="Cover" asp-action="Index" class="btn btn-primary">取消</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
    <script type="text/javascript">
        var type = $("#Colour").val()
        if (type == "蓝领") {
            $("input").css("color", "#0080FF");
            $("h1").html("蓝领");
            $("h1").css("color", "#0080FF");

        } else if (type == "红领") {
            $("input").css("color", "#FF2D2D");
            $("h1").html("红领");
            $("h1").css("color", "#FF2D2D");
        } else if (type == "黄领") {
            $("h1").css("color", "#FFDC35");
            $("h1").html("黄领");
            $("h1").css("color", "#FFDC35");
        };
       
        var type1 = $("#coverType").val();
       
        if (type1 == "入库") {
            $("#workerName").css("display","none");
            $("#departmentName").css("display", "none");
        };
     

    </script>
</body>
</html>

MyWorkManager/Views/Cover/CoverDetail.cshtml
@using MyWorkManager.Models;
@model MyWorkManager.viewModels.CoverDedailParameterViewModel;
@{ ViewBag.Title = "明细查询";}


<div class="container  overflow-auto" style="height:1000px">

    <form class="form-inline" asp-controller="Cover" asp-action="CoverDetail" method="post">
        <div class="form-group">
            <label for="startime">起始时间:</label>
            <input type="date" class="form-control" id="startime" value="@Model.coverParameter.StartTime.ToString("yyyy-MM-dd")" asp-for="@Model.coverParameter.StartTime">
        </div>
        <div class="form-group">
            <label for="endtime">截至时间:</label>
            <input type="date" class="form-control" id="endtime" value="@Model.coverParameter.EndTime.ToString("yyyy-MM-dd")" asp-for="@Model.coverParameter.EndTime">
        </div>
        <div class="form-group">
            <label for="Paypath">颜色:</label>
            <select type="date" class="form-control" id="Paypath" value="" asp-for="@Model.coverParameter.Colour" asp-items="Html.GetEnumSelectList<CoverColour>()">
            </select>
        </div>
        <div class="form-group">
            <label for="Colour">款式:</label>
            <select type="date" class="form-control" id="Colour" value="" asp-for="@Model.coverParameter.Sleeve" asp-items="Html.GetEnumSelectList<CoverSleeve>()">
            </select>
        </div>
        <div class="form-group">
            <label for="Colour">尺寸:</label>
            <select type="date" class="form-control" id="Colour" value="" asp-for="@Model.coverParameter.Size" asp-items="Html.GetEnumSelectList<CoverSize>()">
            </select>
        </div>

        <div class="form-group">
            <label for="Type">类型:</label>
            <select type="date" class="form-control" id="Type" value="" asp-for="@Model.coverParameter.Type">
                <option>全部</option>
                <option>出库</option>
                <option>入库</option>
            </select>
        </div>


        <button type="submit" class="btn btn-default">查询</button>


        <hr style="margin:10px" />

        <table class="table table-bordered" id="ticketnumber">

            <tr>
                <th>日期</th>
                <th>颜色</th>
                <th>款式</th>
                <th>尺寸</th>
                <th>类型</th>
                <th>数量</th>
                <th>领用人</th>
                <th>部门</th>

            </tr>
            @foreach (var item in Model.covers)
            {
                <tr>
                    <th>@item.creatTime</th>
                    <th>@item.Colour</th>
                    <th>@item.Colour</th>
                    <th>@item.Size</th>
                    <th>@item.Type</th>
                    <th>@item.Number</th>
                    <th>@item.workerName</th>
                    <th>@item.departmentName</th>

                </tr>
            }

        </table>
        <nav aria-label="...">
            <ul class="pagination">
                <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
               
                    <li class="active"><a href="#"> <span class="sr-only">(current)</span></a></li>
                
                


            </ul>
            <P>每页数量(@Model.coverParameter.PageSize)</P>
            <P>共(@Model.coverParameter.totalPage)页</P>
        </nav>
    </form>
    @*<script>
        var time = new Date();
        $("#startime").val(time.toJSON().substring(0, 10));
        $("#endtime").val(time.toJSON().substring(0, 10));

    </script>*@
</div>

MyWorkManager/Views/Cover/Index.cshtml
@using MyWorkManager.Models;
@model MyWorkManager.viewModels.CoverStockParameterViewModel;
@{ ViewBag.Title = "库存";}

<script>
    //$(document).ready(function () {
    //    var trcount = $("tr").length;
    //    if (trcount < 2) {
    //        $("#ticketnumber").css("display", "none");

    //    }

    //});
</script>
<div class="container">

    <h2 class="sub-header">Section title</h2>
    
        <form class="form-inline" asp-controller="Cover" asp-action="Index" method="post">
           
            <div class="form-group">
                <label for="Paypath">颜色:</label>
                <select type="date" class="form-control" id="Paypath" value="" asp-for="@Model.coverParameter.Colour" asp-items="Html.GetEnumSelectList<CoverColour>()">
                </select>
            </div>
            <div class="form-group">
                <label for="Colour">款式:</label>
                <select type="date" class="form-control" id="Colour" value="" asp-for="@Model.coverParameter.Sleeve" asp-items="Html.GetEnumSelectList<CoverSleeve>()">
                </select>
            </div>
            <div class="form-group">
                <label for="Colour">尺寸:</label>
                <select type="date" class="form-control" id="Colour" value="" asp-for="@Model.coverParameter.Size" asp-items="Html.GetEnumSelectList<CoverSize>()">
                </select>
            </div>

            <div class="form-group">
                <label for="Type">类型:</label>
                <select type="date" class="form-control" id="Type" value="" asp-for="@Model.coverParameter.Type"   >
                    <option>全部</option>
                   
                </select>
            </div>


            <button type="submit" class="btn btn-default">查询</button>
        </form>
   
    <hr style="margin:10px" />
    <div class="table-responsive">
        <table class="table table-bordered" id="ticketnumber">

            <tr style="text-align:center">
                <th>序号</th>
                <th>颜色</th>
                <th>袖长</th>
                <th>尺寸</th>
                <th>数量</th>
                <th colspan="2"><div class="col-md-4">操作</div></th>
            </tr>
            @{
                int i = 0;
                foreach (var item in Model.covers)
                {
                    i = i + 1;
                    <tr style="text-align:center">
                        <td>@i</td>
                        <td>@item.Colour</td>
                        <td>@item.Sleeve</td>
                        <td>@item.Size</td>
                        <td>@item.Number</td>
                        <td><a asp-controller="Cover" asp-action="AddCover" asp-route-covertype="@item.Colour,@item.Sleeve,@item.Size,入库">入库</a></td>
                        <td><a asp-controller="Cover" asp-action="AddCover" asp-route-covertype="@item.Colour,@item.Sleeve,@item.Size,出库">出库</a></td>

                    </tr>

                }
                <tr>
                    <td>合计</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td colspan="2"><a asp-controller="Cover" asp-action="CoverDetail">查询明细</a></td>
                </tr>

            }

        </table>
    </div>
</div>