MyWorkManager/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWorkManager.Dto;
using MyWorkManager.Models;

namespace MyWorkManager.Controllers
{
  //  [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
       
        private readonly RoleManager<IdentityRole> _roleManager;

        public  RoleController(RoleManager<IdentityRole> roleManager)
        {
           
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles =await  _roleManager.Roles.ToListAsync();
          
           
            return View(roles);
        }
        [HttpGet]
        public IActionResult CreatRole()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreatRole( RoleCreatDto roleCreatDto)
        {
            if (!ModelState.IsValid)
            {
                return View(roleCreatDto);
            }

            var role = await _roleManager.FindByNameAsync(roleCreatDto.name);
            if (role!=null)
            {
                return View(roleCreatDto);
            }
            var newrole = new IdentityRole()
            {

                Name = roleCreatDto.name
            };
            var result = await _roleManager.CreateAsync(newrole);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(roleCreatDto);
        }
    }
}

MyWorkManager/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWorkManager.Dto;
using MyWorkManager.Models;

namespace MyWorkManager.Controllers
{
   // [Authorize(Roles ="Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<IdentityUser> userManager ,RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            this._roleManager = roleManager;
        }

       
        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var users = await _userManager.Users.ToListAsync();
            return View(users);
        }

        [HttpGet]
        public async  Task<IActionResult> UpDataUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            
            LoginModel loginuser= new LoginModel()
            {
                Id = user.Id,
                UserName = user.UserName
                
                
              
            };
            if (user!=null)
            {
                return View(loginuser);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpDataUser(LoginModel loginModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "请输入密码验证");
                return View(loginModel);
            }
           
            var user = await _userManager.FindByIdAsync(loginModel.Id);
            user.UserName = loginModel.UserName;
            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "修改用户失败");
            return View(loginModel);
        }

        public async Task<IActionResult> DeleteUser(string  id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user!=null)
            {
                var reslut = await _userManager.DeleteAsync(user);
                if (reslut.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("","删除失败");
                    return RedirectToAction("Index");
                }
            }
            ModelState.AddModelError("","没有找到要删除的用户");
            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult>EditRolesToUser( string id )
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var user = await _userManager.FindByIdAsync(id);
            List<IdentityRole> inRoles = new List<IdentityRole>();
            foreach (var role in roles)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    inRoles.Add(role);
                   
                }
            }
            foreach (var item in inRoles)
            {
                roles.Remove(item);
            }
            var editUserRoleDto = new EditUserRoleDto()
            {
                Id=user.Id,
                UserName = user.UserName,
                NotInRoles=roles,
                InRoles= inRoles

            };
            return View(editUserRoleDto);
        }
        [HttpGet]
        public async Task<IActionResult>  AddRoleToUser(string ids)
        {
            string[] idstrs = ids.Split(',');
            var user = await _userManager.FindByIdAsync(idstrs[0]);
            var role = await _roleManager.FindByIdAsync(idstrs[1]);
               await _userManager.AddToRoleAsync(user, role.Name);
            var roles = await _roleManager.Roles.ToListAsync();
            
            List<IdentityRole> inRoles = new List<IdentityRole>();
            foreach (var item in roles)
            {
                if (await _userManager.IsInRoleAsync(user, item.Name))
                {
                    inRoles.Add(item);
                  
                }
            }
            foreach (var item in inRoles)
            {
                roles.Remove(item);
            }
            var editUserRoleDto = new EditUserRoleDto()
            {
                Id = user.Id,
                UserName = user.UserName,
                NotInRoles = roles,
                InRoles = inRoles

            };
            return RedirectToAction("EditRolesToUser", editUserRoleDto);

        }
        [HttpGet]
        public async Task<IActionResult> RemoveRoleToUser(string ids)
        {
            string[] idstrs = ids.Split(',');
            var user = await _userManager.FindByIdAsync(idstrs[0]);
            var role = await _roleManager.FindByIdAsync(idstrs[1]);
            await _userManager.RemoveFromRoleAsync(user, role.Name);
            var roles = await _roleManager.Roles.ToListAsync();

            List<IdentityRole> inRoles = new List<IdentityRole>();
            foreach (var item in roles)
            {
                if (await _userManager.IsInRoleAsync(user, item.Name))
                {
                    inRoles.Add(item);

                }
            }
            foreach (var item in inRoles)
            {
                roles.Remove(item);
            }
            var editUserRoleDto = new EditUserRoleDto()
            {
                Id = user.Id,
                UserName = user.UserName,
                NotInRoles = roles,
                InRoles = inRoles

            };
            return RedirectToAction("EditRolesToUser", editUserRoleDto);

        }

    }
}

MyWorkManager/Views/Shared/_Layout.cshtml
@using MyWorkManager.Migrations;
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager;
@inject UserManager<IdentityUser> UserManager;

@*
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->

    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/bootstrap/dist/js/jquery-3.5.1.min.js"></script>
    <script src="~/bootstrap/dist/js/bootstrap.js"></script>


</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">

        <div class="container" style="font-size: 18px">

            <ul class="nav nav-pills " style="float: left">
                <li><a asp-controller="Home" asp-action="Index">主页</a></li>
                <li><a href="#">Projects</a></li>
                <li><a href="#">Services</a></li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        用户管理 <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">

                        <li> <a class="nav nav-pills " asp-area="" asp-controller="User" asp-action="Index">用户管理</a></li>
                        <li> <a class="nav nav-pills " asp-area="" asp-controller="Role" asp-action="Index">角色管理</a></li>

                    </ul>
                </li>
            </ul>
            <form asp-action="Logout" asp-controller="Account" method="post" id="logoutForm" style="float: right">
                <ul class="nav nav-pills  ">
                    @if (SignInManager.IsSignedIn(User))
                    {

                        <li><a href="#">欢迎你：@User.Identity.Name </a></li>
                        <li> <a href="javascript:document.getElementById('logoutForm').submit()">退出</a></li>
                        <li> <a asp-action="Register" asp-controller="Account">注册</a></li>
                    }
                    else
                    {

                        <li><a asp-action="Login" asp-controller="Account">登入</a></li>

                    }
                </ul>
            </form>
        </div>
    </nav>

  


            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>

        </div>
    </div>



</body>
</html>

*@



<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

   

  
    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/bootstrap/dist/js/jquery-3.5.1.min.js"></script>
    <script src="~/bootstrap/dist/js/bootstrap.js"></script>

    <!-- Custom styles for this template -->
    <link href="~/bootstrap/dist/css/dashboard.css" rel="stylesheet">


</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav nav-pills " style="float: left">
                    <li><a asp-controller="Home" asp-action="Index">主页</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Services</a></li>
                    <li> <a class="nav nav-pills " asp-area="" asp-controller="User" asp-action="Index">用户管理</a></li>
                    <li> <a class="nav nav-pills " asp-area="" asp-controller="Role" asp-action="Index">角色管理</a></li>
                </ul>
               
                <form asp-action="Logout" asp-controller="Account" method="post" id="logoutForm" style="float: right">
                    <ul class="nav nav-pills  ">
                        @if (SignInManager.IsSignedIn(User))
                        {

                            <li><a href="#">欢迎你：@User.Identity.Name </a></li>
                            <li> <a href="javascript:document.getElementById('logoutForm').submit()">退出</a></li>
                            <li> <a asp-action="Register" asp-controller="Account">注册</a></li>
                        }
                        else
                        {

                            <li><a asp-action="Login" asp-controller="Account">登入</a></li>

                        }
                    </ul>
                </form>

            </div>
        </div>
    </nav>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Analytics</a></li>
                    <li><a href="#">Export</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="">Nav item</a></li>
                    <li><a href="">Nav item again</a></li>
                    <li><a href="">One more nav</a></li>
                    <li><a href="">Another nav item</a></li>
                    <li><a href="">More navigation</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="">Nav item again</a></li>
                    <li><a href="">One more nav</a></li>
                    <li><a href="">Another nav item</a></li>
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <h1 class="page-header">Dashboard</h1>

                <div class="row placeholders">
                    @RenderBody()
                </div>

                </div>

            </div>
        </div>
   


    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>