MyWorkManager/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace MyWorkManager.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        public DateTime CreateTime { get; set; }
        public string Colour { get; set; }
        public double TicketValue { get; set; }
        [Required(ErrorMessage = "{0}不能为空")]
        [Range(0,10000 ,ErrorMessage ="必须是一个正整数")]
        [Display(Name = "数量")]
        public int Number { get; set; }
        [Required(ErrorMessage ="{0}不能为空")]
        [Display(Name = "金额")]
        public double SumMoneny { get; set; }
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name ="领用人")]
        public string HappenName { get; set; }
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "类型")]
       
        public string Type { get; set; }
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "支付方式")]
        public string Paypath { get; set; }

    }
}

MyWorkManager/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using MyWorkManager.Servers;
using MyWorkManager.Models;
using Microsoft.AspNetCore.Authorization;

namespace MyWorkManager.Controllers
{
    public class TicketController : Controller
    {
        public TicketController(Servers.ITicketRepository ticketRepository)
        {
            _ticketRepository = ticketRepository;
        }

        public ITicketRepository _ticketRepository;
        
        public IActionResult Index()
        {
          var tickets= _ticketRepository.GetAllTicekets().ToList();
           var s= tickets.GroupBy(t =>new { t.Colour ,t.Type,t.TicketValue}).Select(e=>new { Colour= e.Key.Colour, TicketValue=e.Key.TicketValue , Number=e.Sum(t=>t.Number), SumMoneny = e.Sum(t => t.SumMoneny), Type= e.Key.Type }).ToList();
            List<Ticket> tickesgroup = new List<Ticket>();
            foreach (var item in s)
            {
                if (item.Type=="入库")
                {
                    Ticket ticket = new Ticket();
                    ticket.Colour = item.Colour;
                    ticket.TicketValue = item.TicketValue;
                    ticket.Number = item.Number;
                    ticket.SumMoneny = item.SumMoneny;
                    tickesgroup.Add(ticket);
                }
               
            }
            foreach(var item in s)
            {
                foreach (var i in tickesgroup)
                {
                    if (item.Type == "出库" && i.Colour == item.Colour)
                    {
                        i.Number -= item.Number;
                        i.SumMoneny -= item.SumMoneny;
                    }
                }
               
            }
           
            return View(tickesgroup);
        }

       
    }
}

MyWorkManager/Controllers/TicketIAOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWorkManager.Models;

namespace MyWorkManager.Controllers
{
    public class TicketIAOController : Controller
    {

        public Servers.ITicketRepository _ticketRepository;
        public TicketIAOController(Servers.ITicketRepository ticketRepository)
        {
            _ticketRepository = ticketRepository;
        }
        [Authorize]
        [HttpGet]
        public IActionResult Index(string state)
        {
            Ticket ticket = new Ticket();
            if (state!=null)
            {
                string[] s = state.Split(',');
                if (s[0] == "黄色")
                {
                    ticket.Colour = "黄色";
                    ticket.TicketValue = 0.5;
                    ticket.Type = s[1];

                }
                if (s[0] == "红色")
                {
                    ticket.Colour = "红色";
                    ticket.TicketValue = 1;
                    ticket.Type = s[1];

                }
            }
            

            return View(ticket);
        }
        //[HttpPost]
        //public  IActionResult Add(Ticket ticket)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        ticket.CreateTime = DateTime.Now;
        //        _ticketRepository.AddTickets(ticket);
        //        return RedirectToAction("Index", "Ticket");
        //    }
        //    else
        //    {
        //        string state = ticket.Colour + "," + ticket.Type;
        //        ModelState.AddModelError(string.Empty, "不能空值");
        //        return RedirectToRoute(new { Controller= "TicketIAO",Action="Index", state = state });

        //    };
        [Authorize(Roles ="Admin")]
        [HttpPost]
        public IActionResult Index(Ticket ticket)
        {
            if (ModelState.IsValid&&ticket.Paypath!="请选择")
            {
                ticket.CreateTime = DateTime.Now;
                _ticketRepository.AddTickets(ticket);
                return RedirectToAction("Index", "Ticket");
            }
            else
            {
                
                ModelState.AddModelError(string.Empty, "不能空值");
                return View(ticket);

            };
        }
}
}

MyWorkManager/Views/Ticket/Index.cshtml
@model IEnumerable<MyWorkManager.Models.Ticket>;
@{ ViewBag.Title = "库存";}

<script>
    $(document).ready(function () {
        var trcount = $("tr").length;
        if (trcount < 2) {
            $("#ticketnumber").css("display", "none");
           
        }

    });
</script>
<div class="container">

    <h2 class="sub-header">Section title</h2>
    
  
        <div class="table-responsive">
            <table class="table table-bordered" id="ticketnumber">

                <tr style="text-align:center">
                    <th>颜色</th>
                    <th>面值</th>
                    <th>数量</th>
                    <th>金额</th>
                    <th colspan="2"><div class="col-md-4">操作</div></th>
                </tr>
                @{
                    foreach (var item in Model)
                    {

                        <tr style="text-align:center">
                            <td>@item.Colour</td>
                            <td>@item.TicketValue</td>
                            <td>@item.Number</td>
                            <td>@item.SumMoneny</td>
                            <td><a asp-controller="TicketIAO" asp-action="Index" asp-route-state="@item.Colour,入库">入库</a></td>
                            <td><a asp-controller="TicketIAO" asp-action="Index" asp-route-state="@item.Colour,出库">出库</a></td>

                        </tr>

                    }
                    <tr>
                        <td>合计</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td colspan="2"><a asp-controller="TicketQuery" asp-action="Index">查询明细</a></td>
                    </tr>

                }

             </table>
        </div>
 </div>